name: Azure AppService Deploy
on:
  workflow_dispatch:

  permissions:
    id-token:write
    contents:read

env:
  NODEJS_VERSION:20.x

jobs:
  build-deploy:
    runs-on:ubuntsu-latest
    steps:
      -name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

      -name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20
          cache: 'npm'
          Cache-dependency-path: "./package-lock.json" 

      -name: Install dependencies
       run: npm ci

      -name: Build Node.js app
       run: npm run build

      - name: Test Node.js app
        run: npm run test

      - name: Azure login
        uses: azure/login@v1
        with
          client-id: {{ screts_AZURE_CLIENT_ID }}
          tenant-id: {{ screts_AZURE_TENANT_ID }}
          subscription-id: {{ screts_AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Web App
        uses azure/webapps-deploy@v2
        with:
          app-name: {{ screts_AZURE_WEBAPP_NAME }}
          package:
          
      - name: Azure logout
        run: |
          azu logout
      


      