name: Azure AppService Deploy
on: [push]

env:
  AZURE_WEBAPP_PACKAGE_PATH: './published' 

permissions:
  id-token: write
  contents: read


jobs:
  build-deploy:

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20
          cache: 'npm'
          Cache-dependency-path: "./package-lock.json" 

      - name: Install dependencies
        run: npm ci

      - name: Build Node.js app
        run: npm run build

      - name: Test Node.js app
        run: npm run test

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
                    
      - name: Azure logout
        run: |
          az logout

      

          

      